### ISSUE TITLE
Go 1.9 support.

### ISSUE THREAD

**Issue by shurcooL** [golang/gddo#505]
This is a high level tracking issue for https://godoc.org support for Go 1.9. This is largely the same process as every Go release (e.g., see #475). /cc @shantuo

### Tasks

- [x] We need to add support for new Go packages. E.g., https://godoc.org/math/bits is currently 404. (Resolved in code via 936217787a75581223fdad5426c89f45df72b5dc, waiting on deployment.)
- [x] `builtin` package is missing (#503).
- [x] gosrc: error importing package from a directory (#504).
- [x] Search query for `strings` or `os` does not find the corresponding package in stdlib. E.g., https://godoc.org/?q=strings, https://godoc.org/?q=os.

**Comment by myitcv** [comment]
Not sure whether this is related, but ever since the upgrade to Go 1.9 a query for `strings` does not return the `strings` package:

https://godoc.org/?q=strings

<img width="711" alt="screen shot 2017-08-25 at 22 03 19" src="https://user-images.githubusercontent.com/3374574/29732621-41a1f442-89e1-11e7-9455-082d6d609ebc.png">

Similarly affected:

```
os
strings
```

**Comment by shantuo** [comment]
Sorry, it is, we are fixing it.

**Comment by shantuo** [comment]
Seems gddo is running Go 1.9, closing this bug.

**Comment by shurcooL** [comment]
I can confirm all issues are resolved.

Thanks @shantuo! 🎉
